server.port=8081
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/eventos}

# JWT
security.jwt.secret=${JWT_SECRET:change-me-in-dev}
security.jwt.exp-min=${JWT_EXP_MIN:15}
springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/v3/api-docs


APP_DATA_KEY=${APP_DATA_KEY}

spring.data.mongodb.auto-index-creation=true

