server.port=8081
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/eventos}
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASS:guest}

# JWT
security.jwt.secret=${JWT_SECRET:change-me-in-dev}
security.jwt.exp-min=${JWT_EXP_MIN:15}
springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/v3/api-docs


APP_DATA_KEY=${APP_DATA_KEY}

spring.data.mongodb.auto-index-creation=true

app.notifications.exchange=${NOTIFY_EXCHANGE:eventos.notifications.exchange}
app.notifications.queue=${NOTIFY_QUEUE:eventos.notifications.queue}
app.notifications.routing-key=${NOTIFY_ROUTING_KEY:eventos.notifications.created}
app.notifications.enabled=${NOTIFY_ENABLED:true}

